<template><div><TagLinks /><h2 id="background" tabindex="-1"><a class="header-anchor" href="#background" aria-hidden="true">#</a> Background</h2>
<p>Greetings, Final Fantasy TCG enthusiasts! I'm Benny Soo <em>(no, not the Nationals-bound Benny Chan from my local gaming circle)</em>. I'm thrilled to share my recent journey to the Top 8 at the Store Championships at CardArt in Sunnyvale, CA on 6/17/23, which saw a turnout of 27 players, primarily locals with a smattering from across California.</p>
<img src="https://i.imgur.com/zFWa3V9.jpg"/>
<h2 id="the-deck" tabindex="-1"><a class="header-anchor" href="#the-deck" aria-hidden="true">#</a> The Deck</h2>
<p>I had the pleasure of playing a [Wind/Water Warrior of Light (WoL) variant deck] <a href="https://ffdecks.com/deck/4921976914182144">(https://ffdecks.com/deck/4921976914182144)</a>, whimsically named Skyborne Legacy, a nod to my in-progress video game project. This deck idea wasn't premeditated; rather, it serendipitously materialized during my playtesting sessions with the Fire/Wind XIII WoL deck. Thanks to Julian Highsmith for suggesting the Wind Moogle that generated Earth CP, thus propelling this deck idea into reality.</p>
<p>Battling Ice decks with their dull/freeze strategies often put me in a tight spot with my Fire/Wind XIII WoL deck. To tackle this, I incorporated Asura and rethought my approach to activate my forwards. This paved the way for a brand new deck built around activating cards like Rosa, Asura, and Sanctuary Keeper. Also, two Moogles capable of yielding the essential elements to unlock WoL within wind and water made it sweeter.</p>
<p>With the meta being heavily populated by WoL and Shantotto, Chaos/Ark seemed like a logical choice. However, the recent trend of Mono Water decks topping the charts necessitated a rethink. Cue Neo Exdeath! This surprise addition came with a dual advantage: It not only served as a discount for Ark, but also pressured the opponent by delaying their build-up. As a bonus, Neo Exdeath proved to be searchable by Syldra, adding an unexpected edge to my strategy.</p>
<p>Thanks to Peter Wong's suggestion, I incorporated an additional combo: pairing Lulu with my Alexanders. The synergy between Lulu and Alexander—especially against Mono Water decks with their ample monsters—proved irresistible. I believe these combos, along with WoL, formed the backbone of my deck.</p>
<p>How to pilot my deck is simply to build up the 4 Backups necessary to deploy WoL naturally. Ideally, you would want to see Norsch/Waltril, the 2 Moogles, and Yaag Rosch. The Moogles are searchable by Choco/Mog and Syldra. Once WoL comes into play, having Lulu or Rosa can remove most Forwards from the board.</p>
<h2 id="matchups" tabindex="-1"><a class="header-anchor" href="#matchups" aria-hidden="true">#</a> Matchups</h2>
<h3 id="round-1-dragoons-0-1-vs-darayl-top-4" tabindex="-1"><a class="header-anchor" href="#round-1-dragoons-0-1-vs-darayl-top-4" aria-hidden="true">#</a> Round 1 - Dragoons (0-1) vs. Darayl (Top 4)</h3>
<p>Despite a formidable board with Cecil, Tidus, and WoL, I couldn't outmaneuver the Dragoon's board. A Freya Special wiped out my forwards and left me struggling to recover. I did make the grave error of forgetting to use a stolen Ramuh to prevent 2 points of damage which led to my demise.</p>
<h3 id="round-2-dragoons-1-1-vs-jim" tabindex="-1"><a class="header-anchor" href="#round-2-dragoons-1-1-vs-jim" aria-hidden="true">#</a> Round 2 - Dragoons (1-1) vs. Jim</h3>
<p>The earlier encounter with the Dragoons proved enlightening as I came more prepared this time. Some mistakes by my opponent led me to victory, with WoL inflicting persistent damage.</p>
<h3 id="round-3-mono-wind-2-1-vs-benny" tabindex="-1"><a class="header-anchor" href="#round-3-mono-wind-2-1-vs-benny" aria-hidden="true">#</a> Round 3 - Mono Wind (2-1) vs. Benny</h3>
<p>This matchup compelled me to cast Chaos for 9 CP twice, and I also managed to steal a Yuffie the second time to take the game. Rosa and WoL's value and imposing presence helped me deal with 10K forwards effectively. Machine gun WoL did work.</p>
<h3 id="round-4-warrior-of-light-3-1-vs-hikari" tabindex="-1"><a class="header-anchor" href="#round-4-warrior-of-light-3-1-vs-hikari" aria-hidden="true">#</a> Round 4 - Warrior of Light (3-1) vs. Hikari</h3>
<p>Zidane helped me steal beneficial cards like Aria, setting up both proper backups while searching my WoL. Neo Exdeath effectively turned the tide in my favor after taking an initial 5 damage straight. The crippling grasp of Neo Exdeath was an overwhelming threat to my opponent.</p>
<h3 id="round-5-warrior-of-light-4-1-vs-kelly-top-8" tabindex="-1"><a class="header-anchor" href="#round-5-warrior-of-light-4-1-vs-kelly-top-8" aria-hidden="true">#</a> Round 5 - Warrior of Light (4-1) vs. Kelly (Top 8)</h3>
<p>A turn 1 yolo Neo Exdeath left my opponent reeling, and they couldn't recover. They saved their hand and tried to deploy a forward, but that is when I cast Ark on their forward, decimating their hand. Shoutouts to Kevin and Keenith for their talk prior about giving me the confidence to turn 1 Neo Exdeath lol.</p>
<h3 id="top-8-warrior-of-light-0-2-vs-brian-champion" tabindex="-1"><a class="header-anchor" href="#top-8-warrior-of-light-0-2-vs-brian-champion" aria-hidden="true">#</a> Top 8 - Warrior of Light (0-2) vs. Brian (Champion)</h3>
<p>In the first round, poor backup draws left me vulnerable. I made some terrible decisions of stealing the opponent’s Forward and backup. These ultimately were bounced by Unei for their huge CP gain and my terrible board loss. The second round was tighter—I dropped Neo Exdeath mid-game, creating issues for my opponent. However, my attacks caused EX Burst of Cu Sith x2 and a Tyro, handing them a much-needed advantage. They managed to bounce Neo Exdeath while removing it from my hand with Zidane. Ultimately this opponent of mine ended up being the Store Champion.</p>
<h2 id="mvps" tabindex="-1"><a class="header-anchor" href="#mvps" aria-hidden="true">#</a> MVPs</h2>
<p>Warrior of Light was my main damage dealer, and Neo Exdeath emerged as a formidable force, particularly with its synergy with Syldra. Lulu paired with WoL was a powerful combo being able to shoot Forwards down. Also, fetching Ark and Alexanders for repeated value plays.</p>
<h2 id="areas-of-improvement" tabindex="-1"><a class="header-anchor" href="#areas-of-improvement" aria-hidden="true">#</a> Areas of Improvement</h2>
<p>Waltril didn't prove useful, particularly with Norsch already on the field being my only other necessary Wind backup. Mind Flayer and Zidane had their moments stealing cards but losing them to the opponent’s bounce was ultimately painful.</p>
<h2 id="unknown-potential" tabindex="-1"><a class="header-anchor" href="#unknown-potential" aria-hidden="true">#</a> Unknown Potential</h2>
<p>Lightning, which was primarily included for Rydia, never came into play when required. Yuna and Chaos Walker, despite being last-minute tech cards, were never used.</p>
<h2 id="potential-modifications" tabindex="-1"><a class="header-anchor" href="#potential-modifications" aria-hidden="true">#</a> Potential Modifications</h2>
<p>Considering swapping Mind Flayer with the 2 CP Chocobo bounce Summon, adding another Rosa, or a larger-bodied 2 CP Fire/Wind Zidane. The 2 CP Onion Knight that can deploy Lulu/WoL, and 1 CP Geomancer also seem promising. Penelo/Filo instead of the Norsch/Waltril/Clavat combo could also be an option.</p>
<h2 id="conclusion" tabindex="-1"><a class="header-anchor" href="#conclusion" aria-hidden="true">#</a> Conclusion</h2>
<p>I was gearing up to face FFVI, Ice/X, and Mono Water, but the matchups didn't turn out that way. Regardless, my deck flowed smoothly, but I am still curious how it would fare against the above decks. I'm appreciative of the support from the Bay Area Espers and my local community, and I'd like to extend special thanks to Jordan Pang, Jacob Hahn, and Jason Mirkwood Hsieh for their contributions to the event. Feel free to share your suggestions to further refine this deck—I'm all ears!</p>
</div></template>


